"""Enumerate weighted-context interventions on real Dragapult ladder losses.

This is a read-only hypothesis miner.  The replay was generated by the elite
parent, not by the weighted candidate, so a changed action is not assigned a
value label.  The output is intentionally unsuitable for actor training.
"""

from __future__ import annotations

import argparse
from collections import Counter
from datetime import datetime, timezone
import glob
import hashlib
import json
from pathlib import Path
import sys
from typing import Any

import numpy as np


ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from agent import dragapult_bc as D, dragapult_turn_context as C  # noqa: E402
from agent import model, qu_v2_features as FEATURES  # noqa: E402
from agent.obsview import ST_MAIN, ObsView  # noqa: E402
from tools import index_corpus  # noqa: E402
from tools.research.analyze_top_dragapult_divergence import (  # noqa: E402
    coarse,
    decisions,
    registered_decks,
)
from tools.research import eval_dragapult_route_guards as RG  # noqa: E402
from tools.research import eval_md_v2_scaled_gameplay as COMMON  # noqa: E402
from tools.research import train_dragapult_weighted_context_main as TRAIN  # noqa: E402


DEFAULT_DIRECTORIES = (
    ROOT / "tools/checkpoints/ladder-diagnosis-20260811/dragapult",
    ROOT / "tools/checkpoints/elite-ladder-analysis-20260811/dragapult",
)
DEFAULT_OUTPUT = TRAIN.RUN / "ladder-failure-interventions.json"
TEAM = "増殖するG"


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def load_weights(path: Path) -> dict[str, np.ndarray]:
    with np.load(path, allow_pickle=False) as archive:
        return {name: archive[name].copy() for name in archive.files}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("directories", nargs="*", type=Path)
    parser.add_argument("--team", default=TEAM)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    directories = tuple(args.directories) or DEFAULT_DIRECTORIES

    main_net = COMMON._load_net(RG.PATHS["main"], "elite MAIN")
    weights = load_weights(TRAIN.WEIGHTS)
    target = tuple(D.TARGET_DECK)
    files: dict[int, Path] = {}
    for directory in directories:
        for name in glob.glob(str(directory.expanduser() / "*.json")):
            path = Path(name)
            document = json.loads(path.read_text(encoding="utf-8"))
            episode = int((document.get("info") or {}).get("EpisodeId", -1))
            if episode >= 0:
                files[episode] = path

    counts: Counter[str] = Counter()
    opponents: Counter[str] = Counter()
    changes: Counter[str] = Counter()
    examples: list[dict[str, Any]] = []
    for episode, path in sorted(files.items()):
        document = json.loads(path.read_text(encoding="utf-8"))
        decks = registered_decks(document)
        names = (document.get("info") or {}).get("TeamNames") or ()
        rewards = document.get("rewards") or ()
        for seat, deck in decks.items():
            if tuple(sorted(deck)) != target:
                continue
            if seat >= len(names) or names[seat] != args.team:
                continue
            if seat >= len(rewards) or rewards[seat] != -1:
                continue
            counts["loss_seats"] += 1
            opponent_hash = index_corpus.deck_sha256(decks.get(1 - seat, ()))[:10]
            opponents[opponent_hash] += 1
            for obs, logged in decisions(document, seat):
                view = ObsView(obs)
                if view.select_type != ST_MAIN or not view.options:
                    continue
                counts["main_prompts"] += 1
                sample = FEATURES.encode_public_observation(obs, deck)
                logits, _ = main_net.forward(sample)
                base = model.decode_qu_v2(
                    logits, len(view.options), view.min_count, view.max_count,
                )
                parent = D._guard_phantom_completion(view, base)
                if parent != base:
                    counts["completion_protected_prompts"] += 1
                    candidate = parent
                else:
                    candidate = C.apply(view, logits, parent, weights)
                counts["parent_matches_logged"] += list(parent) == list(logged)
                if candidate == parent:
                    continue
                counts["candidate_interventions"] += 1
                before, after = coarse(view, parent), coarse(view, candidate)
                changes[f"{before} -> {after}"] += 1
                if len(examples) < 80:
                    examples.append({
                        "episode_id": episode,
                        "seat": seat,
                        "turn": view.turn,
                        "turn_action_count": (view.current or {}).get("turnActionCount"),
                        "opponent_deck_sha256_prefix": opponent_hash,
                        "parent": before,
                        "candidate": after,
                        "logged": coarse(view, logged),
                    })

    payload = {
        "schema": "ptcg.dragapult-weighted-context.ladder-failure-audit.v1",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "policy_scope": "elite-parent ladder losses only",
        "causal_interpretation": False,
        "actor_training_eligible": False,
        "warning": (
            "The weighted candidate did not generate these trajectories. "
            "Interventions are hypothesis roots, not outcome labels."
        ),
        "team": args.team,
        "directories": [str(path.resolve()) for path in directories],
        "artifacts": {
            "main": {"path": str(RG.PATHS["main"].resolve()),
                     "sha256": sha256_file(RG.PATHS["main"])},
            "adapter": {"path": str(TRAIN.WEIGHTS.resolve()),
                        "sha256": sha256_file(TRAIN.WEIGHTS)},
        },
        "counts": dict(counts),
        "losses_by_opponent_deck_sha256_prefix": dict(opponents),
        "most_common_interventions": dict(changes.most_common(40)),
        "examples": examples,
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(json.dumps({
        "output": str(args.output), "counts": payload["counts"],
        "most_common_interventions": dict(changes.most_common(12)),
    }, ensure_ascii=False, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
